lib/lasso_web/router.ex
defmodule LassoWeb.Router do
  use LassoWeb, :router
  import Plug.BasicAuth
  import Phoenix.LiveView.Router
  import Phoenix.LiveDashboard.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery

    plug :put_secure_browser_headers, %{
      "content-security-policy" =>
        "script-src 'self' 'unsafe-eval' 'unsafe-inline'; img-src 'self'"
    }
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :admins_only do
    plug :basic_auth, Application.compile_env(:lasso, :basic_auth)
  end

  scope "/", LassoWeb do
    pipe_through :browser

    get "/", PageController, :index

    delete "/admin/lasso/:uuid", LassoViewController, :delete
    post "/admin/lasso/", LassoViewController, :new

    get "/lasso/:uuid/view", LassoViewController, :show
  end

  scope "/admin" do
    pipe_through [:browser, :admins_only]
    live_dashboard "/", metrics: LassoWeb.Telemetry
  end

  # The `get` here gets flagged by Sobelow as a potential for  "CSRF via Action Reuse"
  # It does not matter if a user can trigger the post request in this scenario.
  scope "/lasso", LassoWeb do
    get "/:uuid", LassoController, :request
    put "/:uuid", LassoController, :request
    post "/:uuid", LassoController, :request
    delete "/:uuid", LassoController, :request
    patch "/:uuid", LassoController, :request
    options "/:uuid", LassoController, :request
  end
end

lib/lasso_web/templates/page/index.html.eex
<div class="jumbotron">
<img class="img-fluid float-right mt-0 px-3"
    src="<%= Routes.static_path(@conn, "/images/lasso.svg") %>"
    alt="lasso logo"
    height="100px"
    width="100px" />

  <p class="lead">
  A tool to visualize HTTP requests, specifically made for inspecting webhook callbacks.
  </p>

  <hr class="my-4">

  <p>When you create a “lasso”, you’ll get a unique URL that you can use as the destination for HTTP requests. Lasso will receive and store HTTP requests to this endpoint, so you can view and debug the body/headers/params.</p>

  <%= form_for @conn, Routes.lasso_view_path(@conn, :new), [method: :post], fn _f -> %>
      <%= submit "Create new lasso", class: "btn btn-dark btn-lg" %>
  <% end %>
</div>